# Generated by Django 5.0 on 2024-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_confirmationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default=0, verbose_name='код верификации'),
        ),
    ]
