# Generated by Django 5.0 on 2023-12-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=50, verbose_name='разборчивый url')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog', verbose_name='превью')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('count_view', models.PositiveIntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
