# Generated by Django 5.0 on 2024-04-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_deny_publish_product', 'Can cancel publishing'), ('can_edit_desription', 'Able to change description'), ('can_edit_category', 'Can change category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
